### ISSUE TITLE
How to enable Trace_error with fluent-bit kinesis plugin

### ISSUE THREAD

**Issue by atreyd** [aws/amazon-kinesis-streams-for-fluent-bit#161]
How to enable `Trace_error` with fluent-bit kinesis plugin. 
- I have setup a log pipeline with fluentbit and kinesis data streams as output. All microservice containers (ECS) are pushing logs to Standard output and then fluentbit daemon container is picking up logs from stdout and sending to kinesis data streams
- Currently we are facing issues with the Kinesis output plugin where fluentbit is intermittently stops sending logs to kinesis streams. 

During troubleshooting, we often face an issue with limited logging from output side like we don't have visibility of the issues occurred on kinesis streams side. 
Is there any option to enable detailed logging on kinesis output configurations to enable detailed logging like we have for ES output plugin.

**Comment by hossain-rayhan** [comment]
We need to build our image enabling the `FLB_TRACE` option. Then we can set the `Log_Level=trace` in the config. I believe we are not doing this today and this should be an enhancement.

**Comment by atreyd** [comment]
@hossain-rayhan  This FLB_TRACE option is for enabling the detailed logging on fluenbit service (daemon), not on a specific output plugin. I found this option in ES output plugin which seems to be really helpful when troubleshooting the issues with log output.
It will be a good addition for AWS plugins such as S3, Kinesis Firehose and Kinesis Data streams.

**Comment by zhonghui12** [comment]
Hi @atreyd , could we close this issue as it seems like your issue has been resolved by the option? Please let me know if you have another problems here. Thanks.

**Comment by zhonghui12** [comment]
Close this issue for now cause of no response. Please feel free to reopen it and post an update if needed. Thanks.
