### ISSUE TITLE
Add HTTP timeout config for PutRecords call

### ISSUE THREAD

**Issue by jpaskhay** [aws/amazon-kinesis-streams-for-fluent-bit#178]
We're running into an intermittent issue in our environment where the `PutRecords` call in `sendCurrentBatch` hangs in the AWS SDK and times out after 5m30s (we see a read timeout when we patched in appropriate `LogLevelType` settings into the `aws.Config`). When this happens, the request is actually consumed on the Kinesis side, but there appears to be a potential bug in the AWS Go SDK that causes it to fail to parse the response and then retry internally (resulting in duplicates).

We'll be following up in the AWS Go SDK repo in parallel, as this seems similar to issues that have been previously reported for other Kinesis API calls.

In the meantime, we'd like to have the ability to use a smaller timeout to at least reduce the time spent hanging when this occurs. I'll be submitting a PR that allows for configuring the HTTP timeout.

**Comment by zhonghui12** [comment]
Hi @jpaskhay ,
could you explain a little bit about how you test the timeout? I believe it should be something like this:
> we see a read timeout when we patched in appropriate LogLevelType settings into the aws.Config

**Comment by jpaskhay** [comment]
I forgot to update this issue to link to https://github.com/aws/aws-sdk-go/issues/4149 that was mentioned in the original description.

**Comment by zhonghui12** [comment]
This change will be included in our next release.
