### ISSUE TITLE
Truncating after compression

### ISSUE THREAD

**Issue by matthewfala** [aws/amazon-kinesis-streams-for-fluent-bit#183]
I noticed that truncation is occurring after compression in kinesis streams.

I'm not sure that the plugin can truncate compressed data and expect it to still be in a valid compressed format.

here is the plugin's current assumption
```
truncate(compress(data)) == compress(truncate(data))
``` 
Does that hold true for gzip and zlib?

https://github.com/aws/amazon-kinesis-streams-for-fluent-bit/blob/94aa8d778642122125018317d01b6b87f8e58942/kinesis/kinesis.go#L479

If not then the current truncation system may need to be replaced.

**Comment by zhonghui12** [comment]
This fix has been included in latest release: https://github.com/aws/aws-for-fluent-bit/releases/tag/v2.22.0.
