### ISSUE TITLE
Incorrect maximum record size

### ISSUE THREAD

**Issue by falaa** [aws/amazon-kinesis-streams-for-fluent-bit#21]
Sending logs fails due to too large size with the message:

time="2020-03-18T10:46:26Z" level=error msg="[kinesis 0] PutRecords failed with InvalidArgumentException: Records size exceeds 5 MB limit\n\tstatus code: 400, request id: d576e1fc-22dc-c659-839d-1fbe02a45df7\n"

The reason behind is the wrong value for maximumPutRecordBatchSize. The docs say "a limit of 5 MB for the entire request, including partition keys."
https://docs.aws.amazon.com/sdk-for-go/api/service/kinesis/#Kinesis.PutRecords

**Comment by hossain-rayhan** [comment]
Hi @falaa , we put an update to fix this. Please, test with your special case and let us know. Feel free to reopen the issue if needed.

**Comment by falaa** [comment]
Hi @hossain-rayhan, thanks!
I've built it a couple of days ago from your personal repo and as far I did not notice any problems.

**Comment by hossain-rayhan** [comment]
#22

**Comment by falaa** [comment]
Hi,
how's it going with the tests? I'm afraid that this problem still exists, today it occurred with outputPlugin.dataLength = 5242772. Does this 5 MiB limit for the entire request also includes StreamName? Is there anything else in the request? I am wondering because it is still 108 left, and our Stream-name is shorter.
