### ISSUE TITLE
invalid partition key

### ISSUE THREAD

**Issue by daparthi001** [aws/amazon-kinesis-streams-for-fluent-bit#23]
Here is the config
time="2020-04-03T03:37:24Z" level=info msg="[kinesis 0] plugin parameter partition_key = '(container_id, wrong_key)'"
time="2020-04-03T03:37:49Z" level=error msg="[kinesis 0] Invalid partition key. Failed to find partition_key (container_id, wrong_key) in log record {\"log\":\"2020-04-03T03:37:23.134Z\\tINFO\\tlog/harvester.go:255\\tHarvester started for file: /var/lib/docker/containers/8da2b924139c7b60c04f04be15c7bd85313cbea511fbd99b63c171247b01dfd1/8da2b924139c7b60c04f04be15c7bd85313cbea511fbd99b63c171247b01dfd1-json.log\\n\",\"stream\":\"stderr\",\"time\":\"2020-04-03T03:37:23.1342619Z\"}\n"

**Comment by hossain-rayhan** [comment]
Hi @daparthi001 , can you please add the content of your `fluent-bit.conf` file here? It would help us to investigate in a better way. Thanks.

**Comment by daparthi001** [comment]
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  labels:
    app.kubernetes.io/name: fluentbit
data:
  fluent-bit.conf: |
    [SERVICE]
        Parsers_File  parsers.conf
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
    [FILTER]
        Name parser
        Match **
        Parser nginx
        Key_Name log
    [OUTPUT]
        Name            kinesis
        Match           *
        region          us-east-1
        stream         <stream name>
        partition_key   container_id
        append_newline  true
  parsers.conf: |
    [PARSER]
        Name   nginx
        Format regex
        Regex ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")? \"-\"$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
        # Command      |  Decoder | Field | Optional Action
        # =============|==================|=================
        Decode_Field_As   escaped    log

**Comment by daparthi001** [comment]
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit
  labels:
    app.kubernetes.io/name: fluentbit
spec:
  selector:
    matchLabels:
      name: fluentbit
  template:
    metadata:
      labels:
        name: fluentbit
    spec:
      serviceAccountName: fluent-bit
      containers:
      - name: aws-for-fluent-bit
        image: 906394416424.dkr.ecr.us-west-2.amazonaws.com/aws-for-fluent-bit:latest
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
        - name: mnt
          mountPath: /mnt
          readOnly: true
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 100Mi
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      - name: mnt
        hostPath:
          path: /mnt

**Comment by hossain-rayhan** [comment]
Hi @daparthi001 , thanks for providing the information. 
From the output plugin, we can see it's getting `(container_id, wrong_key)` as the value of `partition_key` field.
- [kinesis 0] plugin parameter partition_key = '(container_id, wrong_key)'"

However, in your config file, it's clear that you set `container_id` for the value of `partition_key`. 

I was wondering if we are using the correct config file. I am not an expert in Kubernetes, and I tested the feature on ECS and its working fine. Would you please double check to confirm that we are using the correct config file?

**Comment by hossain-rayhan** [comment]
Hi @daparthi001 , 
Hope you were able to resolve your issue. I am closing this issue for now. Feel free to re-open if you still need an answer.
