### ISSUE TITLE
does it support the output JSON-formatted?

### ISSUE THREAD

**Issue by yutsengwei** [aws/amazon-kinesis-streams-for-fluent-bit#32]
As title, sorry the question is very short.

**Comment by PettitWesley** [comment]
@yutsengwei Sorry 😐, I'm confused by your question...  this plugin sends records as serialized JSON to kinesis. 

For example, a Docker log might look like:

```
{
    "source": "stdout",
    "log": "116.82.105.169 - Homenick7462 197 [2018-11-27T21:53:38Z] \"HEAD /enable/relationships/cross-platform/partnerships\" 501 13886",
    "container_id": "e54cccfac2b87417f71877907f67879068420042828067ae0867e60a63529d35",
    "container_name": "/ecs-demo-6-container2-a4eafbb3d4c7f1e16e00"
}
```

This JSON will be serialized to binary form and then sent as the [data in a single record](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecords.html) in a Kinesis PutRecords call.

**Comment by yutsengwei** [comment]
Hello @PettitWesley, sorry to make you confused, I was wondering if the output is the same as https://github.com/awslabs/aws-fluent-plugin-kinesis JSON.

I am doing research for fluent bit, if it's a different format, then I have to switch back to fluentd.

Thank you for the information!

**Comment by PettitWesley** [comment]
@yutsengwei The output sent to Kinesis should be the same. Both plugins take the incoming msgpack records, create a JSON string from them, and send to Kinesis.

**Comment by hossain-rayhan** [comment]
Hi @yutsengwei , as @PettitWesley mentioned, the output received in Kinesis should be same for both plugins. We are closing this issue. Feel free to reopen if you have any question.
