### ISSUE TITLE
timestamp with sub-second resolution

### ISSUE THREAD

**Issue by rgarcia** [aws/amazon-kinesis-streams-for-fluent-bit#34]
As far as I can tell the code uses https://github.com/lestrrat-go/strftime, which offers a way to include sub-second format strings. It looks like the way the code uses it though does not tap into that feature, which means sub-second resolution format strings are not possible. We would like to have a `time_key_format` that includes nanoseconds.

**Comment by hencrice** [comment]
This was released as part of AWS for Fluent Bit 2.6.0. Closing
