### ISSUE TITLE
Does it support Ouput option Retry_Limit

### ISSUE THREAD

**Issue by yutsengwei** [aws/amazon-kinesis-streams-for-fluent-bit#36]

**Comment by sonofachamp** [comment]
`Retry_Limit` is a Fluent Bit engine feature and is applicable to all output plugins.

References:
* https://docs.fluentbit.io/manual/administration/scheduling-and-retries
* https://github.com/fluent/fluent-bit/issues/309#issuecomment-311685689
* https://github.com/fluent/fluent-bit/issues/860#issuecomment-432718154
