### ISSUE TITLE
lots of records failed to be delivered error logs

### ISSUE THREAD

**Issue by patrickshan** [aws/amazon-kinesis-streams-for-fluent-bit#7]
```
time="2019-12-06T02:33:25Z" level=error msg="[kinesis 0] 1 records failed to be delivered\n"

time="2019-12-06T02:33:25Z" level=error msg="[kinesis 0] 1 records failed to be delivered\n"

time="2019-12-06T02:36:40Z" level=error msg="[kinesis 0] 1 records failed to be delivered\n"

time="2019-12-06T02:37:21Z" level=error msg="[kinesis 0] 1 records failed to be delivered\n"

time="2019-12-06T02:37:30Z" level=error msg="[kinesis 0] 1 records failed to be delivered\n"

time="2019-12-06T02:45:49Z" level=error msg="[kinesis 0] 1 records failed to be delivered\n"
```
we have seen lots of `records failed to be delivered` error logs like the ones pasted above. Looking at the code, it seems that it does retry after those failures and logs another failure `Record failed to send with error` if it failed the retry. I am wondering if it should really be a `warning` since it retries and sends log to kinesis eventually. If not, any recommended way to debug this kind of errors ?

**Comment by hossain-rayhan** [comment]
Added a commit to fix this issue. Closing this for now. Feel free to re-open if needed.
