### ISSUE TITLE
Add supported ECS Agent versions for time_key_format in README.md

### ISSUE THREAD

**Issue by hossain-rayhan** [aws/amazon-kinesis-streams-for-fluent-bit#72]
To get the benefit for setting microsecond, customers need to use the ECS Agent version v1.42.0 or later. One customer created a PR for firehose plugin. We need to update it here as well. 

https://github.com/aws/amazon-kinesis-firehose-for-fluent-bit/pull/63

**Comment by zhonghui12** [comment]
I am working on it
